### ISSUE TITLE
CODE REVIEW

### ISSUE THREAD

**Issue by Amoshalt** [PolytechLyon/isi3-test-tardy_tests#1]
Bonsoir, 
Pourriez vous me donner votre avis sur mon travail s'il vous plait.
J'ai effectué un changement sur les tests de vectorTests car -3 et -33-8 étaient considérés comme int et non BigDecimal (type que retournent les fonctions de la classe Vector).
Je me demandais aussi s'il était normal d'attendre Fizz Buzz suite à l'échange de la règle 2 et 5 car étant donné que c'est la dernière règle qui match est effectuée on a forcément après la règle du multiple par 3 qui vient overwrite le "Fizz Buzz".
Merci d'avance pour votre réponse.

**Comment by Slashgear** [comment]
Ok ça me va, l'usage de l'AtomicReference est un peu fumeuse mais ok. 🤣
